# config_v100.yaml - Memory-efficient configuration for V100 GPUs
model:
  # VAE settings
  vae_base_model: 'medvae_4_1_3d'  # 4x compression per dimension
  latent_channels: 8  # Balanced expressiveness vs memory
  vae_temporal_weight: 0.1
  freeze_vae_after: 5000
  
  # DiT settings - scaled down for V100
  dit_config:
    latent_channels: 8
    latent_size: [6, 32, 32]  # After 8x compression of 82x512x512
    hidden_dim: 512  # Reduced from 768 for V100
    depth: 12  # Reduced from 24
    num_heads: 8
    mlp_ratio: 4.0
    dropout: 0.1
    use_rope: true
  
  # Flow matching settings
  flow_matching_config:
    num_sampling_steps: 50
    sigma_min: 1.0e-5
    use_ode_solver: 'euler'
    time_sampling: 'uniform'
    loss_weighting: 'uniform'
    interpolation_method: 'optimal_transport'

training:
  # Optimization
  vae_lr: 1.0e-4
  dit_lr: 1.0e-4
  weight_decay: 0.01
  grad_clip: 1.0
  
  # Loss weights
  velocity_weight: 1.0
  flf_weight: 0.1
  vae_recon_weight: 1.0
  vae_kl_weight: 0.01
  vae_temporal_weight: 0.1
  
  # Training schedule
  num_epochs: 100
  val_freq: 5
  save_freq: 10
  
  # Batch settings for V100 (16GB)
  batch_size: 1  # Per GPU
  gradient_accumulation_steps: 4  # Effective batch size of 4
  mixed_precision: true
  gradient_checkpointing: true  # Disabled for memory saving
  
  # Scheduler settings
  scheduler_type: 'cosine'  # 'cosine', 'linear', or 'constant'
  warmup_epochs: 5

data:
  # Data settings - Updated for NumPy array structure
  num_frames: 42  # Full interpolated sequence length from target_frames.npy
  input_frames: 10  # Number of input frames from input_frames.npy
  target_size: [512, 512, 82]  # [H, W, T] - actual data dimensions
  
  # Image processing settings
  intensity_window: [-1000, 500]  # Lung window (HU values)
  normalize: true  # Apply lung windowing and normalize to [-1, 1]
  
  # Data augmentation settings
  augmentation:
    intensity_scale: 0.05  # Random intensity scaling
    intensity_shift: 0.05  # Random intensity shifts
    noise_std: 0.01  # Random noise
    enable_augmentation: true  # Enable during training
  
  # Phase range settings - for full breathing cycle
  phase_range: '0-50'  # Full breathing cycle (no filtering)
  
  # Experiment filtering (optional - can filter specific interpolation methods)
  # experiment_filter: ['hfr_optical_flow_8fps', 'hfr_linear_8fps']  # Uncomment to filter
  
# Inference settings
inference:
  guidance_scale: 1.0
  num_sampling_steps: 50
  batch_size: 1  # Small batch for inference due to image size